import logging
from typing import (
    Dict,
    List,
    Optional,
    Type,
)

from pydantic import (
    BaseModel,
    Field,
)

from mindful.llm.llm_base import ToolDefinition

logger = logging.getLogger(__name__)


class TapeMetadata(BaseModel):
    """Structure for Tape metadata generated by the Mindful Agent."""

    category: str = Field(default="", description="A single, broad classification category for the content.")
    context: str = Field(default="", description="Concise situational or thematic context (max ~2-3 sentences).")
    keywords: List[str] = Field(default_factory=list, description="A list of 2-5 relevant keywords.")


class TapeInsight(BaseModel):
    should_archive: bool = Field(default=False, description="True if tape seems redundant/obsolete.")
    updated_metadata: Optional[TapeMetadata] = Field(
        default=None, description="Suggested new metadata if improvements found."
    )
    new_links: Optional[Dict[str, str]] = Field(
        default=None,
        description="Suggested new links from target tape: {neighbor_tape_id: 'description of relationship'}.",
    )


def pydantic_to_openai_tool(model: Type[BaseModel], name: str, description: str) -> ToolDefinition:
    """
    Convert a Pydantic model to an OpenAI function tool definition.
    """
    try:
        schema = model.model_json_schema()
    except Exception as e:
        logger.error(f"Failed to generate schema for {model.__name__}: {e}")
        raise ValueError(f"Invalid schema for {model.__name__}")

    tool_def = {
        "type": "function",
        "function": {
            "name": name,
            "description": description,
            "parameters": {
                "type": "object",
                "properties": schema["properties"],
                "required": schema.get("required", []),
            },
        },
    }

    return tool_def
