from pydantic import BaseModel, Field
from typing import List


class TapeMetadata(BaseModel):
    """Structure for Tape metadata generated by the Mindful Agent."""

    category: str = Field(..., description="A single, broad classification category for the content.")
    context: str = Field(..., description="Concise situational or thematic context (max ~2-3 sentences).")
    keywords: List[str] = Field(default_factory=list, description="A list of 2-5 relevant keywords.")
